import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  tutorialSidebar: [
    {
      type: "category",
      label: "Início",
      items: ["welcome", "contribute", "news"],
    },
    {
      type: "category",
      label: "Primeiros Passos",
      items: [
        "getting-started/what-is-modding",
        {
          type: "category",
          label: "Configurando o Ambiente",
          items: [
            "getting-started/setup/windows",
            "getting-started/setup/macos",
            "getting-started/setup/linux",
          ],
        },
        "getting-started/mod-structure",
        "getting-started/first-mod",
      ],
    },
    {
      type: "category",
      label: "Fundamentos",
      items: [
        "fundamentals/mod-lifecycle",
        "fundamentals/event-system",
        "fundamentals/config-files",
        "fundamentals/resource-management",
        "fundamentals/localization",
      ],
    },
    {
      type: "category",
      label: "Blocos",
      items: [
        "blocks/basic-blocks",
        "blocks/block-properties",
        "blocks/block-behaviors",
        "blocks/block-states",
        "blocks/block-entities",
        "blocks/block-rendering",
      ],
    },
    {
      type: "category",
      label: "Itens",
      items: [
        "items/basic-items",
        "items/item-properties",
        "items/item-behaviors",
        "items/tools-weapons",
        "items/consumables",
        "items/block-interactions",
      ],
    },
    {
      type: "category",
      label: "Entidades",
      items: [
        "entities/entity-system",
        "entities/creating-entities",
        "entities/entity-behaviors",
        "entities/animations",
        "entities/ai-pathfinding",
        "entities/player-interactions",
      ],
    },
    {
      type: "category",
      label: "Interface e GUI",
      items: [
        "gui/gui-system",
        "gui/creating-interfaces",
        "gui/slots-inventories",
        "gui/custom-hud",
        "gui/dialog-elements",
      ],
    },
    {
      type: "category",
      label: "Mecânicas de Jogo",
      items: [
        "gameplay/crafting-systems",
        "gameplay/world-generation",
        "gameplay/biomes-climate",
        "gameplay/physics",
        "gameplay/trading-systems",
        "gameplay/quests-objectives",
      ],
    },
    {
      type: "category",
      label: "Áudio e Visual",
      items: [
        "audio-visual/sounds-music",
        "audio-visual/3d-models",
        "audio-visual/particles",
        "audio-visual/visual-effects",
        "audio-visual/shaders",
      ],
    },
    {
      type: "category",
      label: "Rede e Multijogador",
      items: [
        "networking/data-sync",
        "networking/network-packets",
        "networking/client-server",
        "networking/server-considerations",
      ],
    },
    {
      type: "category",
      label: "Avançado",
      items: [
        "advanced/mod-api",
        "advanced/harmony-patching",
        "advanced/performance",
        "advanced/debugging-tools",
        "advanced/mod-interop",
        "advanced/publishing",
      ],
    },
    {
      type: "category",
      label: "Referências",
      items: [
        "references/official-api",
        "references/glossary",
        "references/faq",
        "references/external-resources",
        "references/api-changelog",
      ],
    },
    {
      type: "category",
      label: "Exemplos",
      items: [
        "examples/code-library",
        "examples/sample-mods",
        "examples/case-studies",
        "examples/design-patterns",
      ],
    },
    {
      type: "category",
      label: "Comunidade",
      items: [
        "community/channels",
        "community/events",
        "community/mod-showcase",
        "community/wiki-contribution",
      ],
    },
  ],
};

export default sidebars;
